security:
  oauth2:
    client:
      clientId: statistics-service
      # clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      clientSecret: 123456
      # accessTokenUri: http://auth-service:5100/uaa/oauth/token
      accessTokenUri: http://localhost:5100/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      # host: statistics-mongodb
      host: localhost
      username: user
      # password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /statistics
  port: 7100

rates:
  url: https://api.exchangeratesapi.io